export const styles = `
.ds{color:#e8eff5;font-size:13px;line-height:1.4;padding:0 16px 16px;--ds-muted:#a0b2c2;--ds-line:#2a3947;font-variant-numeric:tabular-nums}
.ds *{box-sizing:border-box}.ds button{font-family:inherit}.ds .ds-nav{display:flex;gap:4px;padding:3px;background:#111b24;border:1px solid #293744;border-radius:5px;margin:2px 0 8px}
.ds .ds-nav button,.ds .ds-ranges button,.ds .ds-power-modes button,.ds .ds-mini-button{min-width:0;min-height:0!important;width:auto!important;border:0!important;border-radius:3px!important;padding:5px 6px!important;font-size:13px!important;line-height:18px!important;background:transparent!important;color:#aab9c6;box-shadow:none!important;flex:1}
.ds .ds-nav button[aria-pressed=true]{background:#263c4e!important;color:#fff}.ds .ds-ranges button[aria-pressed=true]{background:#263c4e!important;color:#71bfff}
.ds button.gpfocus,.ds button:focus-visible{transform:none!important;background:#eff6fc!important;color:#11202e!important;outline:2px solid #8fcfff!important;outline-offset:1px}
.ds .ds-action{min-width:0!important;width:100%!important;max-width:100%!important;flex:1 1 0!important;font-size:13px!important;min-height:34px!important;padding:7px 6px!important;line-height:20px!important;border-radius:3px!important;background:#263745!important;color:#e8eff5}
.ds .ds-ranges{display:flex;gap:3px;margin:5px 0}.ds .ds-ranges button{font-size:12px!important;padding:3px 4px!important}
.ds-topline{display:flex;align-items:center;justify-content:space-between;color:var(--ds-muted);font-size:11px;letter-spacing:.2px;margin-bottom:4px;gap:6px}.ds-record{display:flex;align-items:center;gap:6px;color:#b3cbbb}.ds-dot{width:5px;height:5px;border-radius:50%;background:#53d8a4;display:inline-block}
.ds-card{border:1px solid var(--ds-line);background:linear-gradient(135deg,#182733,#15222d);border-radius:5px;padding:8px;min-width:0;overflow:hidden}.ds-card-title{display:flex;align-items:center;justify-content:space-between;font-size:12px;font-weight:500;color:#b7c6d2;gap:4px}.ds-card-title svg{vertical-align:-2px;margin-right:5px}
.ds-value{font-size:23px;font-weight:600;line-height:1.2;letter-spacing:-.6px;margin:4px 0;color:#f4f8fb}.ds-unit{font-size:12px;font-weight:400;letter-spacing:0;color:var(--ds-muted);margin-left:4px}.ds-subvalue{font-size:10px;color:var(--ds-muted);white-space:nowrap}
.ds-two{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:8px}.ds-power{margin-top:8px}.ds-power-head{display:flex;align-items:center;justify-content:space-between;gap:4px}.ds-power .ds-value{margin:0}.ds-power-modes{display:flex;gap:3px;margin-top:4px}.ds .ds-power-modes button{width:auto!important;min-width:0!important;flex:0 1 auto!important}.ds .ds-power-modes button{font-size:11px!important;padding:2px 5px!important;border:1px solid transparent!important;flex:none}.ds .ds-power-modes button[aria-pressed=true]{border-color:#56624e!important;color:#f5c779;background:#2a302d!important}
.ds-chart{position:relative;margin-top:6px;overflow:hidden}.ds-chart canvas{display:block}.ds-chart-scale,.ds-chart-floor{position:absolute;right:2px;top:1px;font-size:9px;color:#8ea3b4;background:#16232dea;padding-left:3px;pointer-events:none}.ds-chart-floor{top:auto;bottom:0}.ds-chart-empty{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;color:#93a7b7;font-size:11px}.ds-chart-caption{font-size:10px;color:#a1b2c0;display:flex;justify-content:space-between;margin-top:5px}
.ds-telemetry{margin-top:11px;border-top:1px solid var(--ds-line);padding-top:8px}.ds-kv{display:flex;align-items:baseline;justify-content:space-between;gap:8px;padding:5px 0;font-size:12px}.ds-kv dt{color:var(--ds-muted);flex-shrink:0}.ds-kv dd{margin:0;text-align:right;overflow-wrap:anywhere;color:#e2ebf2}.ds-kv-long{display:block}.ds-kv-long dd{text-align:left;margin-top:3px;font-size:12px;color:#d1dde6;line-height:1.6}.ds dl{margin:0}
.ds .ds-kv.gpfocus{background:#263d4e;outline:1px solid #a7ccea;outline-offset:2px}.ds-section{margin-top:17px}.ds-section h3{margin:0 0 7px;color:#85a2b9;font-size:11px;font-weight:600;letter-spacing:1px}.ds-section .ds-kv{border-bottom:1px solid #233441;padding:7px 0}.ds-device-name{font-size:18px;font-weight:600;line-height:1.35;margin:3px 0;color:#f0f6fa}.ds-tag{display:inline-block;border:1px solid #34516a;background:#1a3042;padding:2px 6px;border-radius:3px;color:#8ecbfb;font-size:11px}
.ds-address{font-family:ui-monospace,monospace;overflow-wrap:anywhere;font-size:18px;line-height:1.5;color:#eaf5ff;margin:6px 0}.ds-address-muted{letter-spacing:1px;color:#95afc4}.ds-note{font-size:11px;color:var(--ds-muted);line-height:1.65;margin:8px 0}.ds-error{color:#ffd19d;background:#352b22;border-left:2px solid #e7a965;padding:8px;margin:8px 0;font-size:12px;overflow-wrap:anywhere}.ds-success{color:#71d9b3;font-size:12px;margin:8px 0}.ds-summary{white-space:pre-wrap;overflow-wrap:anywhere;font:11px/1.6 ui-monospace,monospace;background:#101b24;padding:9px;border-radius:3px;color:#bcd0de}
.ds-actions{display:flex;gap:6px;margin-top:10px}.ds-footer{display:flex;justify-content:space-between;font-size:10px;color:#8199ad;border-top:1px solid var(--ds-line);margin-top:14px;padding-top:8px}.ds-progress{height:3px;border-radius:2px;background:#273d4e;margin:2px 0 6px;overflow:hidden}.ds-progress>span{display:block;height:100%;background:#8ba5ff}
.ds-select{margin:10px 0}.ds-select [role=combobox]{width:100%;min-width:0;font-size:13px;min-height:34px}.ds select{color:inherit}.ds .ds-loading{padding:20px 0;color:var(--ds-muted);text-align:center}
.ds .ds-action.gpfocus,.ds .ds-nav button.gpfocus,.ds .ds-ranges button.gpfocus,.ds .ds-power-modes button.gpfocus{background:#eff6fc!important;color:#11202e!important;outline:2px solid #8fcfff!important;outline-offset:1px}
`;
